// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/shoppers": {
            "get": {
                "description": "Retrieve a list of all shoppers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shoppers"
                ],
                "summary": "Get all shoppers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ShoppersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new shopper with the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a new shopper",
                "parameters": [
                    {
                        "description": "Shopper object to be created",
                        "name": "shopper",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Shopper"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created shopper object",
                        "schema": {
                            "$ref": "#/definitions/main.Shopper"
                        }
                    },
                    "400": {
                        "description": "Error response",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/shoppers/{username}": {
            "get": {
                "description": "Retrieve a shopper by their username",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shoppers"
                ],
                "summary": "Get shopper by username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shopper Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Shopper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update a shopper's information by their username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shoppers"
                ],
                "summary": "Update shopper by username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shopper Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Shopper object to update",
                        "name": "shopper",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Shopper"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Shopper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a shopper by their username",
                "tags": [
                    "shoppers"
                ],
                "summary": "Delete shopper by username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shopper Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "main.Shopper": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "dateJoined": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "zipCode": {
                    "type": "string"
                }
            }
        },
        "main.ShoppersResponse": {
            "type": "object",
            "properties": {
                "shoppers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Shopper"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
